### PR TITLE
toggle all

### PR DESCRIPTION
**Pull request by AnisyaPurnama**

### CODE REVIEW

**Comment by bermarte** [comment]
I am sorry but I can't merge it right now, I have spent quite some time downloading, cloning, and testing our branch but there's a problem. Not sure what is it. The code looks okay but it doesn't run as it should.

It's nice the way the `every()` function is used, but there's no need to put the `toggleAll()` function inside the `Todo` class.

Please run the code, see what is the problem. try to fix it, indent the code and when is ok we will merge it.

**Comment by bermarte** [comment]
Please run the code, see what is the problem. try to fix it, indent the code and when is ok we will merge it.

**Comment by KrystynaMil** [comment]
It doesn't work .... I can't find the problem

**Review by Brainketunze — COMMENTED** [review]
To me the codes seem ok and if is not working, it mean the toggle-all button is not needed in the project. Maybe we need to toggle one after another than to toogle all instead.

**Comment by AnisyaPurnama** [comment]
Yes you right @bermarte , I thought it was okay when i run it before. But something wrong in this branch, I will try to find the problem.

**Pull request closed without merging**
