### PR TITLE
6. classes

### PR DESCRIPTION
**Pull request by bermarte**
### 6. classes
- [x] create a todo class
- [ ] input validation (check the length of the input: it shouldn't be empty or not longer than a given number)
- [ ] style it (this could be the task of somebody else)
- [ ] refactor it (maybe removing the 'save' button)
- [ ] implement the save functionality
- [ ] connect to the back-end
---
Basic class to be styled, changed or trashed (not sure).

One element is:

```html
<li class="todo-lists" id="1613637910570">
   <span class="done" onclick="this.nextElementSibling.innerHTML = &quot;<del>testing</del>&quot;">done</span>
   <div class="li-text" contenteditable="true">testing</div>
   <div>
      <span class="edit">save</span>&nbsp;
      <span class="delete" onclick="this.parentNode.parentNode.remove()">delete</span>
   </div>
</li>
```
The save functionality is not implemented yet, so if you click "Done" but have changed the text, it will not remember the changes in the text.

### CODE REVIEW

**Comment by bermarte** [comment]
The ID is a data object, we can start with no data and using that number for the ID. If you feel comfortable doing this, you can directly model the component in HTML and send it to me. I used span as a button but tried not to use any style or a very simple one. SPAN elements can be stylized, using icons and things. I would suggest copying and pasting the HTML above and pasting it inside the UL element of the HTML page to better shape it. The structure should be the one below. However, we can decide to modify the elements and perhaps remove the "save" button because it will be saved automatically. I would keep it simple. 
Cannot use buttons because `position: absolute` or fixed width and height were used. 

```html
<ul>
  <li></li>
  <li></li>
  <li></li>
</ul>
```

Or we have a wireframe that we will try to implement. Personally, I would remove the "Save" button. But the figma file might take this HTML provided above as a kind of reference.

**Comment by bermarte** [comment]
I'm leaving today but will be back around 3pm.

**Review by KrystynaMil — APPROVED** [review]

**Comment by KrystynaMil** [comment]
Good work @bermarte . I need some time to check and understand all the changes you made :) We can meet around 3 pm if its ok with others ?

**Comment by bermarte** [comment]
> Good work @bermarte . I need some time to check and understand all the changes you made :) We can meet around 3 pm if its ok with others ?

@KrystynaMil I am not sure when I will be back, it could be between 15 and 16 pm. I'll catch you later and ask how is going (if I am not able to be here on time).

**Comment by bermarte** [comment]
The save functionality is not implemented yet, so if you click "Done" but have changed the text, it will not remember the changes in the text.

**Review by AnisyaPurnama — APPROVED** [review]
👍 👍

**Pull request merged**
